package org.owasp.astf.reporting;

import java.io.IOException;

import org.owasp.astf.core.result.ScanResult;

/**
 * Interface for report generators that produce different output formats.
 * <p>
 * The report generator is responsible for transforming scan results into
 * a specific output format such as JSON, HTML, XML, or SARIF. Each implementation
 * of this interface handles a specific format and provides appropriate formatting
 * and styling for that format.
 * </p>
 */
public interface ReportGenerator {

    /**
     * Generates a report from scan results and writes it to the specified path.
     *
     * @param result The scan result containing findings and metadata
     * @param outputPath The file path where the report should be written
     * @throws IOException If an error occurs while writing the report
     */
    void generateReport(ScanResult result, String outputPath) throws IOException;

    /**
     * Gets the name of this report generator.
     *
     * @return A descriptive name for this report generator
     */
    String getName();

    /**
     * Gets the file extension for reports generated by this generator.
     *
     * @return The file extension (without the dot) for generated reports
     */
    String getFileExtension();
}